site_name: CodeGraphContext
theme:
  name: material
nav:
  - Home: index.md
  - Installation: installation.md
  - Use Cases: use_cases.md
  - Architecture: architecture.md
  - CLI Reference: cli.md
  - Server: server.md
  - Core Concepts: core.md
  - Tools: tools.md
  - Cookbook: cookbook.md
  - Contributing:
    - Overview: contributing.md
    - Adding New Languages: contributing_languages.md
  - Troubleshooting: troubleshooting.md
  - Future Work: future_work.md
  - License: license.md