name: Build Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install .[dev]

      - name: Build package
        run: python -m build
